### ISSUE TITLE
Config does not work with docusaurus

### ISSUE THREAD

**Issue by layershifter** [sjwall/mdx-mermaid#67]
**Version**

1.3.2

**Describe the bug**

The issue started as "dark theme does not work".

**To Reproduce**
1. Open https://stackblitz.com/edit/github-pwuwsv-hvqsdq
2. Open "Tutorial" page that uses mermaid
3. See a graph.

**Expected behavior**

![image](https://user-images.githubusercontent.com/14183168/192320603-f1b78999-cd8f-45ae-8889-08a09f927908.png)

Uses dark theme.

**Actual behavior**

![image](https://user-images.githubusercontent.com/14183168/192320703-c0728f12-be99-4588-aff3-2e9581e76d77.png)

Uses light theme.

**Additional context**

I debugged it a bit and it seems that `configSrc` there is always `undefined`:

https://github.com/sjwall/mdx-mermaid/blob/5b229593e821005a64100122bb10f05eec22c3a7/src/Mermaid.tsx#L43

![image](https://user-images.githubusercontent.com/14183168/192321169-83b8392d-e9ba-40bf-a93f-8bfd7a14eee7.png)

This does not seem correct, so in https://github.com/microsoft/griffel/pull/217 I monkey patched it and then it worked, but this does not seem like a proper solution.

Please let me know if it's a setup problem, but in sandbox (https://stackblitz.com/edit/github-pwuwsv-hvqsdq) I have a config exactly like in docs.

**Comment by JPeer264** [comment]
Hey I am facing the same issue, according to the patch you attached it seems that the config is always undefined, thus it will never enter the initialize where the dark theme is attached [here](https://github.com/sjwall/mdx-mermaid/blob/main/src/Mermaid.tsx#L73).

A quickfix for your (or in general every setup) could be to have following in the docusaurus config `[mdxMermaid.default, {}]` (as seen here: https://stackblitz.com/edit/github-pwuwsv-kx6yjx?file=docusaurus.config.js).

But to fix the actual problem is to have either a default for the config or allow empty configs [here](https://github.com/sjwall/mdx-mermaid/blob/main/src/Mermaid.tsx#L74-L78) in the `useEffect` as well. If @sjwall agrees in initializing mermaid without config then I can add a PR

**Comment by slorber** [comment]
FYI official Docusaurus support is coming with https://github.com/facebook/docusaurus/pull/7490
